
# 유저
CREATE TABLE IDUS_USER (
   ID        INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME      VARCHAR(50) NOT NULL COMMENT '이름',
   NICKNAME  VARCHAR(100) NOT NULL COMMENT '닉네임',
   PASSWORD  VARCHAR(100) NOT NULL COMMENT '비밀번호',
   PHONE     VARCHAR(20) NOT NULL COMMENT '전화번호',
   EMAIL     VARCHAR(100) NOT NULL COMMENT '이메일',
   GENDER    VARCHAR(10) COMMENT '성별',

   KEY IDX_USER_PHONE (PHONE),
   KEY IDX_USER_EMAIL (EMAIL)
) ENGINE=InnoDB COMMENT='회원속성';

# 주문
CREATE TABLE IDUS_ORDER (
    ID              VARCHAR(12) NOT NULL PRIMARY KEY,
    USER_ID         INT NOT NULL COMMENT '유저아이디',
    ORDER_NAME      VARCHAR(100) NOT NULL COMMENT '제품명',
    ORDER_DATETIME  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '결제일시',

    KEY IDX_ORDER_USER_ID (USER_ID)
) ENGINE=InnoDB COMMENT='주문속성';

# 이모지 추가
ALTER TABLE IDUS_ORDER
CHARACTER SET = utf8mb4 ,
COLLATE = utf8mb4_unicode_ci;